upgpkg: pulumi 3.0.0-2

diff --git a/pulumi/PKGBUILD b/pulumi/PKGBUILD
--- a/pulumi/PKGBUILD
+++ b/pulumi/PKGBUILD
@@ -4,17 +4,16 @@
 # Contributor: Felix Erkinger <wuxxin@gmail.com>
 
 pkgname=pulumi
-pkgver=3.150.0
 pkgrel=2
+pkgver=3.0.0
 pkgdesc='Modern Infrastructure as Code'
 arch=('x86_64')
 url="https://github.com/$pkgname/$pkgname"
 license=('Apache')
 depends=('glibc')
-makedepends=('go')
-source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz")
-b2sums=('6bef2b28cbdf8dbc69efd365aeceab3a77c359a423ec78813b569195a13ecc3666d7630a2a58e1161a87f0055f2bf84979342ff520faaa01d60dde6acb0c6287')
-options=() # disable as soon as LTO problems are resolved
+makedepends=('go' 'git')
+source=("$pkgname::git+$url.git")
+sha256sums=(SKIP)
 
 _plugin_dirs=(
   "python/cmd/pulumi-language-python"
@@ -22,15 +21,30 @@ _plugin_dirs=(
   "go/pulumi-language-go"
 )
 
-build() {
-  local _work_dir _pkg_dir _sdk_dir _bin_dir _cwd 
-  local _plugin_dir _plugin_path _plugin_name _lang_name lang_dir
-  _work_dir="${srcdir}/${pkgname}-${pkgver}"
-  _pkg_dir="${_work_dir}/pkg"
-  _sdk_dir="${_work_dir}/sdk"
-  _bin_dir="${_work_dir}/bin"
+pkgver() {
+  set -x  # Enable command tracing
 
+  pwd  # Print the current working directory BEFORE the cd
+  cd "$pkgname" || { echo "cd to $pkgname failed!"; exit 1; } # Print error and exit if cd fails
+  pwd  # Print the current working directory AFTER the cd
+
+  # Check if it's a git repository
+  if ! git rev-parse --is-inside-work-tree; then
+    echo "Not a git repository or any of the parent directories!"
+    exit 1
+  fi
+
+  git status  # Show git status (helps diagnose repository issues)
+
+  echo "$(git describe --tags --abbrev=0 | sed 's/^v//')"
+
+  set +x  # Disable command tracing
+}
+
+build() {
+  _work_dir="${srcdir}/${pkgname}"
   cd "${_work_dir}"
+
   export CGO_CPPFLAGS="${CPPFLAGS}"
   export CGO_CFLAGS="${CFLAGS}"
   export CGO_CXXFLAGS="${CXXFLAGS}"
@@ -38,44 +52,30 @@ build() {
   export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
 
   # Build the `pulumi` executable
-  cd "${_pkg_dir}"
-  go build \
-    -ldflags "-linkmode external
-              -X github.com/pulumi/pulumi/sdk/v${pkgver%%.*}/go/common/version.Version=${pkgver}" \
-    -o "${_bin_dir}/${pkgname}" \
-    "./cmd/${pkgname}" \
+  cd "${_work_dir}/pkg"
+  go build -ldflags \
+    "-linkmode external -X github.com/pulumi/pulumi/sdk/v${pkgver%%.*}/go/common/version.Version=${pkgver}" \
+    -o "${_work_dir}/bin/${pkgname}" "./cmd/${pkgname}"
 
   # Build the plugins
-  cd "${_sdk_dir}"
+  cd "${_work_dir}/sdk"
   for _plugin_path in "${_plugin_dirs[@]}"; do
-    _plugin_name="${_plugin_path##*/}"
-    _lang_name="${_plugin_path%%/*}"
-    _lang_dir="${_sdk_dir}/${_lang_name}"
-    _plugin_dir="${_sdk_dir}/${_plugin_path}"
-    _cwd="${PWD}"
-    cd "${_plugin_dir}"
-
-    go build \
-      -ldflags "-linkmode external
-                -X github.com/pulumi/pulumi/sdk/v${pkgver%%.*}/go/common/version.Version=${pkgver}" \
-      -o "${_bin_dir}/${_plugin_name}" \
-      .
-    # copy additional files per plugin
-    if test "${_lang_name}" = "python"; then
-      cp ${_sdk_dir}/${_lang_name}/cmd/pulumi-language-python-exec "${_bin_dir}"
-      cp ${_sdk_dir}/${_lang_name}/dist/pulumi-resource-pulumi-python "${_bin_dir}"
-      cp ${_sdk_dir}/${_lang_name}/dist/pulumi-analyzer-policy-python "${_bin_dir}"
-    elif test "${_lang_name}" = "nodejs"; then
-      cp ${_sdk_dir}/${_lang_name}/dist/pulumi-resource-pulumi-nodejs* "${_bin_dir}"
-	    cp ${_sdk_dir}/${_lang_name}/dist/pulumi-analyzer-policy* "${_bin_dir}"
-    fi
-
-    cd "${_cwd}"
+    cd "${_work_dir}/sdk/${_plugin_path}"
+    go build -ldflags \
+      "-linkmode external -X github.com/pulumi/pulumi/sdk/v${pkgver%%.*}/go/common/version.Version=${pkgver}" \
+      -o "${_work_dir}/bin/${_plugin_path##*/}" .
   done
+
+  # copy additional files of plugins
+  cp ${_work_dir}/sdk/python/cmd/pulumi-language-python-exec "${_work_dir}/bin"
+  cp ${_work_dir}/sdk/python/dist/pulumi-resource-pulumi-python "${_work_dir}/bin"
+  cp ${_work_dir}/sdk/python/dist/pulumi-analyzer-policy-python "${_work_dir}/bin"
+  cp ${_work_dir}/sdk/nodejs/dist/pulumi-resource-pulumi-nodejs* "${_work_dir}/bin"
+  cp ${_work_dir}/sdk/nodejs/dist/pulumi-analyzer-policy* "${_work_dir}/bin"
 }
 
 package() {
-  cd "${srcdir}/${pkgname}-${pkgver}"
+  cd "${srcdir}/${pkgname}"
 
   # Install all executables
   for f in ./bin/*; do
